name: remote ssh command for deploy
on:
  push:
    branches: [develop]
jobs:
  build:
    name: Build
    if: github.repository == 'parallelspaceInc/poly-web'
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          key: ${{ secrets.DEV_KEY }}
          port: ${{ secrets.DEV_PORT }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            ~/poly/start.sh
